-- 코드를 작성해주세요
SELECT I.ITEM_ID,	ITEM_NAME,	RARITY
FROM  ITEM_INFO AS I
JOIN ITEM_TREE AS T
ON I.ITEM_ID = T.ITEM_ID
WHERE NOT EXISTS (
    SELECT PARENT_ITEM_ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID = I.ITEM_ID
)
ORDER BY I.ITEM_ID DESC