-- 코드를 입력하세요
SELECT PRODUCT_CODE,
        (PRICE * SUM_SALES ) AS SALES
FROM PRODUCT
JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SUM_SALES
     FROM OFFLINE_SALE
     GROUP BY PRODUCT_ID) AS PRODUCT_SALES
USING (PRODUCT_ID)
ORDER BY SALES DESC, PRODUCT_CODE ASC;