-- 코드를 입력하세요
SELECT C.CAR_ID, 
        C.CAR_TYPE,	
        ROUND( DAILY_FEE * 30 * (1-DISCOUNT_RATE/100),0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV')
    AND P.DURATION_TYPE = '30일 이상' 
    AND ROUND( DAILY_FEE * 30 * (1-DISCOUNT_RATE/100),0)   >= 500000 
    AND ROUND( DAILY_FEE * 30 * (1-DISCOUNT_RATE/100),0)  < 2000000
    AND C.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE (START_DATE <= '2022-11-30' AND END_DATE>='2022-11-01')
    )
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;