-- 코드를 입력하세요
SELECT ANIMAL_ID,
        O.ANIMAL_TYPE AS ANIMAL_TYPE,
        O.NAME AS NAME
FROM ANIMAL_INS AS I
JOIN ANIMAL_OUTS AS O
USING (ANIMAL_ID)
WHERE I.SEX_UPON_INTAKE LIKE 'Intact%' AND
   ( O.SEX_UPON_OUTCOME LIKE 'Spayed%' OR
    O.SEX_UPON_OUTCOME LIKE 'Neutered%'
    );
