-- 코드를 입력하세요
SELECT NAME,
        DATETIME
FROM ANIMAL_INS AS I
WHERE NOT EXISTS (SELECT ANIMAL_ID
                 FROM ANIMAL_OUTS AS O
                 WHERE I.ANIMAL_ID = O.ANIMAL_ID )
ORDER BY DATETIME ASC
LIMIT 3;