-- 코드를 작성해주세요
SELECT A.ID,
        B.FISH_NAME,
        A.LENGTH
FROM FISH_INFO AS A
JOIN FISH_NAME_INFO AS B
USING (FISH_TYPE)
WHERE A.LENGTH = (SELECT MAX(C.LENGTH) 
                FROM FISH_INFO AS C
                WHERE A.FISH_TYPE = C.FISH_TYPE)   
ORDER BY ID ASC;